# Generated by Django 5.2.2 on 2026-08-26 13:31

import core.fields
from django.db import migrations, models


# Substring of endpoint_url -> provider_type, for classifying rows that predate
# the provider_type field (including the one seeded by migration 0002).
_ENDPOINT_HINTS = (
    ("integrate.api.nvidia.com", "nvidia"),
    ("api.anthropic.com", "anthropic"),
    ("generativelanguage.googleapis.com", "gemini"),
    ("api.groq.com", "groq"),
    ("api.openai.com", "openai"),
)


def backfill_provider_type(apps, schema_editor):
    AIProvider = apps.get_model("core", "AIProvider")
    for pk, endpoint_url in AIProvider.objects.values_list("pk", "endpoint_url"):
        endpoint = (endpoint_url or "").lower()
        for hint, provider_type in _ENDPOINT_HINTS:
            if hint in endpoint:
                # update() avoids a full save(), which would re-encrypt api_key.
                AIProvider.objects.filter(pk=pk).update(provider_type=provider_type)
                break


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovider',
            name='provider_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('gemini', 'Google Gemini'), ('groq', 'Groq'), ('nvidia', 'NVIDIA NIM'), ('other', 'Other (OpenAI-compatible)')], default='other', help_text="Selects the provider's default endpoint and request dialect.", max_length=20),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='api_key',
            field=core.fields.EncryptedTextField(help_text='Encrypted at rest with FIELD_ENCRYPTION_KEY; never displayed once saved.'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='endpoint_url',
            field=models.URLField(blank=True, help_text="Leave blank to use the selected provider type's default base URL."),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Exactly one provider is active; activating this one deactivates the rest.'),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='model_name',
            field=models.CharField(blank=True, help_text='Exact model ID to send, e.g. gpt-5.2, claude-opus-5, gemini-3-pro.', max_length=150),
        ),
        migrations.RunPython(backfill_provider_type, migrations.RunPython.noop),
    ]
