# Generated by Django 5.2.2 on 2026-08-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aiprovider_provider_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_phrase', models.CharField(help_text="Lowercase phrase to match in speech, e.g. 'open whatsapp' or 'whatsapp khol do'.", max_length=120, unique=True)),
                ('action_url', models.URLField(help_text='Web URL opened in a new tab, e.g. https://web.whatsapp.com', max_length=500)),
                ('native_scheme', models.CharField(blank=True, help_text='Optional custom scheme tried first on mobile, e.g. whatsapp://send', max_length=200)),
                ('label', models.CharField(blank=True, help_text="Shown in the toast, e.g. 'WhatsApp'. Defaults to the trigger phrase.", max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'voice command',
                'ordering': ['trigger_phrase'],
            },
        ),
    ]
