# Generated by Django 5.2.2 on 2026-08-29 10:32

import chatbot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_uploadeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='cloudinary_resource_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='cloudinary_url',
            field=models.URLField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='cloudinary_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=chatbot.models.upload_to_user_folder),
        ),
    ]
